#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm constant/geometry/boundaryLayer.obj > /dev/null 2>&1

rm -f constant/extendedFeatureEdgeMesh/* > /dev/null 2>&1
rmdir constant/extendedFeatureEdgeMesh > /dev/null 2>&1

#------------------------------------------------------------------------------
