#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh

runApplication surfaceFeatures

runApplication snappyHexMesh -overwrite

runApplication setFields

# runApplication createBaffles -overwrite

decomposePar

# runApplication $application
runApplication mpirun --use-hwthread-cpus -np 20  $application -parallel

reconstructPar

#------------------------------------------------------------------------------
